version: '3.7'
services:
  alpine:
    build: .
    container_name: alpine-latest
    environment:
      TZ: Asia/Shanghai
    image: v8fg/alpine:latest
    stdin_open: true
    tty: true 
    restart: 'no' # no|on-failure[:max-retries]|always|unless-stopped
    command: [ "/bin/bash"]
